STORAGE_IN_BYTES = 1.44 * 1024 * 1024
PAGES_IN_BOOK = 100
STRINGS_ON_PAGE = 50
SYMBOLS_IN_STRING = 25
SIZE_OF_SYMBOLS_IN_BYTE = 4
SIZE_OF_A_BOOK_IN_BYTE = PAGES_IN_BOOK * STRINGS_ON_PAGE * SIZE_OF_SYMBOLS_IN_BYTE * SYMBOLS_IN_STRING

print("Количество книг, помещающихся на дискету:", int(STORAGE_IN_BYTES // SIZE_OF_A_BOOK_IN_BYTE))